simulation:
  name: "hand_free"
  path: "xmls/shadow_hand/scene_right_free.xml"
  sensors: True
  algo: "polo_td"

mppi:
  n_steps: 100
  n_rollouts: 500
  lambda: 0.5
  initial_control: "random"     # random or zeros
  baseline: True
  gamma: 0.99
  td_step: 55

costs:
  control_weight: 1e-4
  quat_weight: 10.0
  finger_weight: 0.1
  terminal_weight: 5.0

hand:
  qpos_init: "default"               #default, manual or random
  goal_quat: [0.0, 0.0, 1.0, 0.0]

network: 
  network_dims: [68,128,128,64,1]    #mx.nq is 32; mx.nv is 30 so first layer is 62
  update_frequency: 10
  mini_batch: 5
  grad_steps: 0
  net_update_type: "random"     # random or optimal
  load_model: True        
  save_model: False