simulation:
  name: "hand_fixed"
  path: "xmls/shadow_hand/scene_right.xml"
  sensors: False

mppi:
  n_steps: 50
  n_rollouts: 100
  lambda: 0.5
  initial_control: "random"            #random, ones or zeros

costs:
  control_weight: 1e-4
  quat_weight: 10.0
  finger_weight: 0.0
  terminal_weight: 5.0

hand:
  qpos_init: "manual"               #default, manual or random
  goal_quat: [0.0, 0.0, 1.0, 0.0]    


# [1.0, 0.0, 0.0, 0.0]    # no rotation
# [0.0, 1.0, 1.0, 0.0]    # 180 deg aroung x-axis
# [0.0, 0.0, 1.0, 0.0]    # 180 deg aroung y-axis
# [0.0, 0.0, 0.0, 1.0]    # 180 deg aroung z-axis
