simulation:
  name: "hand_fixed"
  path: "xmls/shadow_hand/scene_right.xml"
  sensors: True

mppi:
  n_steps: 100
  n_rollouts: 100
  lambda: 0.8
  initial_control: "zeros"            #random, ones or zeros

costs:
  control_weight: 1e-4
  quat_weight: 1.0
  finger_weight: 0.01
  terminal_weight: 5.0

hand:
  qpos_init: "default"               #default, manual or random
  goal_quat: [0.0, 0.0, 1.0, 0.0]    

