# config/params.yaml
simulation:
  name: "cartpole"          
  path: "xmls/cartpole.xml"

mppi:
  n_steps: 50
  n_rollouts: 100
  lambda: 0.8
  initial_control: "random"     # random or zeros
  baseline: True

costs:
  control_weight: 1e-3
  terminal_weight: 1.0