# config/params.yaml
simulation:
  name: "cartpole"          
  path: "xmls/cartpole.xml"
  algo: "vanilla_mppi"          # this should be the same as the folder holding this file

mppi:
  n_steps: 50
  n_rollouts: 100
  lambda: 0.1
  initial_control: "random"     # random or zeros
  baseline: True

costs:
  control_weight: 1e-3
  terminal_weight: 1.0